# Generated by Django 5.2.5 on 2025-08-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fun', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
